// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmqboqkhbzqtjxyhbaum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtcWJvcWtoYnpxdGp4eWhiYXVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NjgwMjMsImV4cCI6MjA2NzM0NDAyM30.DR3Er4mg7aOHiEPHw036JQB8mdc2TxaNIdsdg5G_6eo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});